accepted = [
  "GPL-1.0",
  "GPL-2.0",
  "GPL-3.0",
  "LGPL-2.0",
  "LGPL-2.1",
  "LGPL-3.0",
  "AGPL-3.0",
  "AGPL-3.0-or-later",
  "EUPL-1.2",
  "MIT",
  "Apache-2.0",
  "MPL-2.0",
  "ISC",
  "Unicode-DFS-2016",
  "Unicode-3.0",
  "OpenSSL",
  "BSD-3-Clause",
  "Zlib",
  "BSD-2-Clause",
  "Unlicense",
]
