[package]
name = "actor-macro"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["parsing", "printing"] }
proc-macro2 = "1.0"
